name: Build

on:
  push:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build Linux binaries
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Install dependencies
        run: sudo apt install make automake libtool bison flex libxaw7-dev
      - name: Build
        run: |
          cd isotel-ngspice
          export DESTDIR=$PWD/install
          ./compile_linux.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux x86_64 binaries release
          path: isotel-ngspice/install
  linux_shared:
    runs-on: ubuntu-latest
    name: Build Linux shared libraries
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Install dependencies
        run: sudo apt install make automake libtool bison flex
      - name: Build
        run: |
          cd isotel-ngspice
          export DESTDIR=$PWD/install
          ./compile_linux_shared.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux x86_64 shared libraries release
          path: isotel-ngspice/install
  win32:
    runs-on: windows-latest
    name: Build Windows x86 binaries
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Setup apt-cyg
        run: |
          lynx -source rawgit.com/transcode-open/apt-cyg/master/apt-cyg > apt-cyg
          install apt-cyg /bin
          apt-cyg install make automake libtool bison flex
      - name: Build
        run: |
          cd isotel-ngspice
          ./cross-compile.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows x86 binaries release
          path: isotel-ngspice/release-mingw-32/ngspice-mingw-32.zip
