name: Build

on:
  push:
  workflow_dispatch:

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build Linux x86_64 binaries
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Install dependencies
        run: sudo apt install make automake libtool bison flex libxaw7-dev
      - name: Build
        run: |
          cd isotel-ngspice
          export DESTDIR=$PWD/install
          ./compile_linux.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux x86_64 binaries release
          path: isotel-ngspice/install
  linux_shared:
    runs-on: ubuntu-latest
    name: Build Linux x86_64 shared libraries
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Install dependencies
        run: sudo apt install make automake libtool bison flex
      - name: Build
        run: |
          cd isotel-ngspice
          export DESTDIR=$PWD/install
          ./compile_linux_shared.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Linux x86_64 shared libraries release
          path: isotel-ngspice/install
  win64:
    runs-on: windows-latest
    name: Build Windows x64 binaries
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Install dependencies
        run: |
          /c/msys64/usr/bin/pacman -S gcc mingw-w64-x86_64-autotools automake make libtool bison flex --noconfirm
      - name: Build
        run: |
          export PATH=$PATH:/c/msys64/usr/bin:/c/msys64/bin
          cd isotel-ngspice
          export DESTDIR=$PWD/install
          /c/msys64/usr/bin/bash ./compile_min.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows x64 binaries release
          path: isotel-ngspice/install
  win64_shared:
    runs-on: windows-latest
    name: Build Windows x64 shared libraries
    defaults:
      run:
        shell: bash
    steps:
      - name: Clone repo
        run: git clone https://github.com/kicad-qemu/isotel-ngspice
      - name: Install dependencies
        run: |
          /c/msys64/usr/bin/pacman -S gcc mingw-w64-x86_64-autotools automake make libtool bison flex --noconfirm
      - name: Build
        run: |
          export PATH=$PATH:/c/msys64/usr/bin:/c/msys64/bin
          cd isotel-ngspice
          export DESTDIR=$PWD/install
          /c/msys64/usr/bin/bash ./compile_min_shared.sh
      - name: Upload built artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Windows x64 shared libraries release
          path: isotel-ngspice/install
